/**
 * Desktop Curate section — one image per cell, none of which appear in
 * workGalleryImages. Index order matches desktopCurateReplacementCells.imageIndex
 * in src/lib/workColumnLayout.ts.
 *
 * Generated by `npm run optimize:curate` — WebP 1600px wide, ≤400 KB each.
 */
export const curateDesktopImages = [
  "/work/curate/curate-desktop-0.webp", // LSB — yacht charter photography
  "/work/curate/curate-desktop-1.webp", // ATM — lifestyle portrait
  "/work/curate/curate-desktop-2.webp", // Soren — editorial portrait
  "/work/curate/curate-desktop-3.webp", // Centurion Boats — portrait
  "/work/curate/curate-desktop-4.webp", // Nautique — detail collage
  "/work/curate/curate-desktop-5.webp", // Wake Dubai — editorial portrait
  "/work/curate/curate-desktop-6.webp", // Interior design — landscape
] as const;

/**
 * Mobile Curate stack — 3 slots, distinct from desktop picks and workGalleryImages.
 * Generated by `npm run optimize:curate` — WebP 1200px wide, ≤400 KB each.
 * Replaces the old mobileCurateImages.ts picks (which were resized portfolio-1/2/3).
 */
export const curateMobileImages = [
  "/work/mobile/curate-1.webp", // Supreme — boat among trees
  "/work/mobile/curate-2.webp", // CREED — aerial dune, lone figure
  "/work/mobile/curate-3.webp", // Lifestyle — editorial portrait
] as const;
