/**
 * Desktop Curate section — one image per cell, none of which appear in
 * workGalleryImages. Index order matches desktopCurateReplacementCells.imageIndex
 * in src/lib/workColumnLayout.ts.
 *
 * Generated by `npm run optimize:curate` — WebP 1600px wide, ≤400 KB each.
 */
export type CurateImage = { src: string; alt: string };

export const curateDesktopImages: readonly CurateImage[] = [
  { src: "/work/curate/curate-desktop-0.webp", alt: "LSB luxury yacht gliding through Dubai waters" },
  { src: "/work/curate/curate-desktop-1.webp", alt: "ATM lifestyle portrait from Arabian Travel Market" },
  { src: "/work/curate/curate-desktop-2.webp", alt: "Søren editorial portrait — Danish cellist" },
  { src: "/work/curate/curate-desktop-3.webp", alt: "Centurion Boats portrait — towboat on open water" },
  { src: "/work/curate/curate-desktop-4.webp", alt: "Nautique Super Air detail collage" },
  { src: "/work/curate/curate-desktop-5.webp", alt: "Wake Dubai editorial portrait on the water" },
  { src: "/work/curate/curate-desktop-6.webp", alt: "Interior design — cinematic brutalist landscape" },
] as const;

/**
 * Mobile Curate stack — 3 slots, distinct from desktop picks and workGalleryImages.
 * Generated by `npm run optimize:curate` — WebP 1200px wide, ≤400 KB each.
 * Replaces the old mobileCurateImages.ts picks (which were resized portfolio-1/2/3).
 */
export const curateMobileImages: readonly CurateImage[] = [
  { src: "/work/mobile/curate-1.webp", alt: "Supreme boat among trees" },
  { src: "/work/mobile/curate-2.webp", alt: "CREED — aerial dune with lone figure" },
  { src: "/work/mobile/curate-3.webp", alt: "Lifestyle editorial portrait" },
] as const;
