/**
 * Curate section image picks.
 *
 * Desktop: curateDesktopImages is derived programmatically from workGalleryImages
 * so that each Curate cell shows the SAME image that appears in the Work gallery
 * at the same cell index. This preserves the Curate→Work frosted-transition handoff
 * (each cell morphs into the corresponding Work tile).
 * imageIndex 0–6 → first 7 entries of workGalleryImages in order.
 *
 * Mobile: curateMobileImages are distinct editorial picks — mobile has no shared-image
 * handoff and these must remain as-is.
 */

import { workGalleryImages } from "@/constants/workGalleryImages";
import { getWorkGalleryProject } from "@/constants/workGalleryProjects";

export type CurateImage = { src: string; alt: string };

/** Desktop Curate cells — one per cell (imageIndex 0–6), matched to workGalleryImages. */
export const curateDesktopImages: readonly CurateImage[] = workGalleryImages
  .slice(0, 7)
  .map((src) => {
    const project = getWorkGalleryProject(src);
    return {
      src,
      alt: project ? `${project.title} — work gallery preview` : "Work gallery preview",
    };
  });

/**
 * Mobile Curate stack — 3 slots, distinct from desktop picks and workGalleryImages.
 * Generated by `npm run optimize:curate` — WebP 1200px wide, ≤400 KB each.
 * Replaces the old mobileCurateImages.ts picks (which were resized portfolio-1/2/3).
 */
export const curateMobileImages: readonly CurateImage[] = [
  { src: "/work/mobile/curate-1.webp", alt: "Supreme boat among trees" },
  { src: "/work/mobile/curate-2.webp", alt: "CREED — aerial dune with lone figure" },
  { src: "/work/mobile/curate-3.webp", alt: "Lifestyle editorial portrait" },
] as const;
